name: server
description: A sample command-line application.
version: 1.0.0

environment:
    sdk: '>=2.14.2 <3.0.0'

dependencies:
    path: ^1.8.0
    dio: ^4.0.1
    alfred: ^0.1.5+1

dev_dependencies:
    flutter_lints: ^1.0.4
    test: ^1.16.0
